Upgrade pip before installing cryptography
Fixes error:

```
Collecting cryptography>=2.1.4 (from azure-keyvault~=1.0->azure==4.0.0->osmosis-azure-driver==0.1.0->ocean-provider==0.4.17)
  Downloading https://files.pythonhosted.org/packages/10/91/90b8d4cd611ac2aa526290ae4b4285aa5ea57ee191c63c2f3d04170d7683/cryptography-35.0.0.tar.gz (559kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2ly4m541/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2ly4m541/cryptography/
The command '/bin/sh -c python3.8 -m pip install .' returned a non-zero code: 1
```