Pin itsdangerous=2.0.1 and revert flask to 1.1.2.
  * Using flask 1.1.4 caused dependency conflict with black:

    ERROR: Cannot install ocean-provider because these package versions have conflicting dependencies.

	The conflict is caused by:
	    black 22.1.0 depends on click>=8.0.0
	    flask 1.1.4 depends on click<8.0 and >=5.1
  * Solution based on: https://serverfault.com/a/1094095