Arweave Integration Milestone 1: Publish using transaction ID (#485)
* Add test scaffold for arweave fileinfo

* first cut at arweave fileinfo tests

* Update get_download_url to support Arweave

* Add ARWEAVE_GATEWAY to README and pytest.ini

* Fix syntax, remove extra `:`

* Rearrange assertions, print result if status not "200 OK"

* Update FileInfoRequest validation to accept type=arweave

* Fix syntax

* Fix content length

* Fix test_check_arweave_bad

* Run pre-commit checks

* Add first cut at download test using arweave file

* Update validate_url_object to work with arweave

* Pass download_url to check_url_details() instead of url_object["url"]

* Remove is_safe_url check and `url` arg from `build_download_response`.

  * When calling download, `is_safe_url()` is called earlier by
    `check_url_details()` so calling again in `build_download_response`
    is redunant.
  * When calling computeResult, `validate_url=False` so `is_safe_url()`
    check is skipped anyway.

* Account for larger latency in GH Actions.

* Add compute test using dataset stored in arweave

* Fix build_download_response so filename doesn't leak arweave tx id

* Update fileinfo error logic to better bubble up Exception messages.

* Improve tests

* Fix syntax error

* Fix tests

* Generalize file dict: "value" instead of "url", "hash", "transactionId"

* Fix test

* Revert "Generalize file dict: "value" instead of "url", "hash", "transactionId""

This reverts commits:
  * deb5d693a0b4070f5374140cc28944a126bcfbdf
  * 9dc6fa4117fa2078a37cf2332c6297cebccfac17

* Remove unnecessary patches for is_safe_url

* Simulate revert of nonce erroneous commit.

* Add try/except back into fileinfo

* Fixup merge

* Add Arweave file type

* Add arweave to list of acceptable types in fileinfo validate_and_create

* Rename test to better describe what it's testing

* Add malformed arweave url_object to test_validate_url_object

* Reinstate test_util.py::test_build_download_response_arweave

* Reinstate arweave related tests

* Update error message

* Remove unnecessary code

* Make Arweave capitalized

* Fix expected exception type

* Remove is_safe_url check from `build_download_response`.

  * When calling download, `is_safe_url()` is called earlier by
    `check_details()` so calling again in `build_download_response`
    is redunant.
  * When calling computeResult, `validate_url=False` so `is_safe_url()`
    check is skipped anyway.

* Fix build_download_response so filename doesn't leak arweave tx id or ipfs hash

* Upgrade IPFS test to check for CID leak

* Fix debug log statement and add missing error check after calling check_details

* Discard benign MismatchedABI warnings

* Remove Content-Length check from arweave fileinfo test

* Remove extra argument

* Fix method name

* Attempt to fix test_compute_arweave

* Try to fix the alg filesChecksum use in test_compute_arweave

* Add Asset type hints to improve method discovery in IDEs like VSCode.

* Fix test_compute_areweave

* Make error message more explicit

* Revert all formatting-only changes.

* Revert a few more formatting-only changes

* Move `magic` import above the `artifacts` import

* Update test to match error message when transactionId key is missing

* Add ALLOWED_FILE_TYPES to avoid duplicating list [ipfs,url,arweave]

* Adjust tests such that assets stored in arweave allow all algorithms

* Specify alg_diff arg name for clarity

* Add ARWEAVE_TRANSACTION_ID constant that points to branin.arff

* Remove the result check from `test_compute_arweave`

* Add assertion about the downloaded contents

* Remove try/except. Exceptions are caught by errorhandler

* Add test where ARWEAVE_GATEWAY is invalid

* Revert "Remove Content-Length check from arweave fileinfo test"

This reverts commit 0024c2618aeef80b23430c2132cf08ad2853723c.

* Add assertion to see what result is when ARWEAVE_GATEWAY is bad

* Empty commit to re-run CI.

* Fix test case where ARWEAVE_GATEWAY is not reachable

* Remove unnecessary snippet

* Fix content lenght (because using branin.arff file now)

* Add --verbose flag to pytest command

* Wait until test_compute_specific_algo_dids finishes compute job

  - Trying to fix error in test_compute (the following test):
    ```
	>       assert response.status == "200 OK", f"start compute job failed: {response.data}"
	E       AssertionError: start compute job failed: b'{"error": "`agreementId` already in use for other job."}'
	E       assert '400 BAD REQUEST' == '200 OK'
	E         - 200 OK
	E         + 400 BAD REQUEST
	```

* Fix contentType

* Revert "Wait until test_compute_specific_algo_dids finishes compute job"

This reverts commit 06327be651fca8d5f236d1a9743a491fb03e7c53.

* Revert "Add --verbose flag to pytest command"

This reverts commit f60f915f5f61a743d39906d79abcc24ce1bda945.

* Separate compute test with auth token to ensure agreementId uniqueness.

* Revert "Remove is_safe_url check from `build_download_response`."

This reverts commit 29f85a9643f380758969f905feda61577bac5344.

* Revert formatting-only changes

* Remove comment.

* Add newline

* Remove headers and userdata for arweave type per comment from @alexcos20

  - https://github.com/oceanprotocol/docs/pull/1082#issuecomment-1208100832

* Revert more formatting only changes

* Add newline at end of file

* Revert "Remove headers and userdata for arweave type per comment from @alexcos20"

This reverts commit 61ff964776c4b4fc8d56da2b9ab4d99028bcdfad.

* Fix test_validate_url_object

* Empty commit to re-run the CI checks with updated barge

* Fix test_compute_paid_env. Use `mint` instead of `transfer`

  - Fix error message:
  >       fee_token.functions.transfer(consumer_wallet.address, to_wei(80)).transact(
            {"from": deployer_wallet.address}
        )
E           web3.exceptions.ContractLogicError: execution reverted: VM Exception while processing transaction: revert ERC20: transfer amount exceeds balance

Co-authored-by: Calina Cenan <calina@cenan.net>