Try upgrading to Flask 1.1.4 to fix error in CI
  * E   ImportError: cannot import name 'json' from 'itsdangerous' (/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/itsdangerous/__init__.py)
  * Solution from: https://serverfault.com/questions/1094062